# Generated by Django 5.0.3 on 2024-03-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TribeniHospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionist',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
